name: Waka Readme

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  SHOW_LINES_OF_CODE: "True"
                  SHOW_TOTAL_CODE_TIME: "True"
                  SHOW_PROFILE_VIEWS: "True"
                  SHOW_COMMIT: "False"
                  SHOW_DAYS_OF_WEEK: "True"
                  SHOW_LANGUAGE: "True"
                  SHOW_OS: "True"
                  SHOW_PROJECTS: "False"
                  SHOW_LOC_CHART: "False"
                  COMMIT_BY_ME: "True"
